[package]
name = "xnb"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]
license = "MIT"
edition = "2018"

[dependencies]
byteorder = "1"
bitreader = "0.1"
lzxd = "0.1"

[dev_dependencies]
image = "0.10"
squish = { git = "https://github.com/jdm/squish-rs.git" }