[package]
name = "xnb"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]

[dependencies]
byteorder = "0.5"
bitreader = "0.1"

[dev_dependencies]
image = "0.10"
squish = {path = "../squish-rs"}